### ISSUE TITLE
Gallery: Stretched image for album cover

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/NV-Global-Tiling#123]
![image](https://cloud.githubusercontent.com/assets/12888048/11027428/3c9b2b1c-86f0-11e5-84e5-daceae7c2df3.png)

**Comment by romatitan** [comment]
Kindly check again the compact album

**Comment by romatitan** [comment]
Kindly check again the compact album

**Comment by christiancebudigital** [comment]
these are not blurred images, these are cropped image of next gen, see attached image, for comparison and setting of next gen gallery set up for compact album.
![notcropped](https://cloud.githubusercontent.com/assets/11186331/11054986/2ad26f9a-87ad-11e5-93b9-842b4deb3a5c.jpg)
![blurred image of no ovride](https://cloud.githubusercontent.com/assets/11186331/11054988/2ad7cf44-87ad-11e5-8d89-3b9057228125.jpg)
![settings thumbnails](https://cloud.githubusercontent.com/assets/11186331/11054987/2ad7c2ce-87ad-11e5-8abc-184cee8ed484.jpg)
![regenerate img](https://cloud.githubusercontent.com/assets/11186331/11054990/2b03abdc-87ad-11e5-8714-af1920dea1f8.jpg)
