### ISSUE TITLE
Clarification: Images at the top of the featured testimonials

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/NV-Global-Tiling#19]
![image](https://cloud.githubusercontent.com/assets/12888048/10241216/8eb53a1e-6918-11e5-96b4-90075e516aaf.png)

**Comment by christiancebudigital** [comment]
Hi Roma,

The red labeled text was not answered with our query before, but i have updated the scope to use gallery acf on option page.

**Comment by romatitan** [comment]
Should it auto play/slide?
http://kenwheeler.github.io/slick/
