### ISSUE TITLE
Homepage: Welcome content has #ffffff background. It should be #000000

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/NV-Global-Tiling#27]
Note: Welcome note font color wil be #ffffff

![image](https://cloud.githubusercontent.com/assets/12888048/10242795/0e4c0de0-6926-11e5-9785-4d22269b2de5.png)

**Comment by christiancebudigital** [comment]
there was a note on the ticket that: NOTE:	overiding design - When building the site, please make all text boxes white with black writing.  The designer did one of the pages (About Us) in this format.
	 - black box with white text will be converted to white box and black tex

**Comment by romatitan** [comment]
@christiancebudigital ,

The designer provides a new design version for About Us page ( 02b-NVG-About-us ), it seems to be used as reference to override the other inner pages.

As well as, the designer provides a new  home page design.
Kindly check and confirm with the PM.
01b-NVG-Homepage.psd

01b-NVG-Homepage.jpg
![01b-nvg-homepage](https://cloud.githubusercontent.com/assets/12888048/10748575/ab7aeb5c-7c9c-11e5-86b9-426d7ea2dc8f.jpg)

**Comment by romatitan** [comment]
The designer provides a new design version for About Us page that seems to be used as reference to override the other inner pages only because there's a new version for home page (01b-NVG-Homepage) as well
