### ISSUE TITLE
Enhancement - Project: To be consistent with the other pages, kindly change the pagination font-family and font-size to titillium_webbold, 18px. Its hover state color to #ef4c28

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/NV-Global-Tiling#53]
![image](https://cloud.githubusercontent.com/assets/12888048/10274620/636ec044-6b72-11e5-94ae-6c2cb10e03cb.png)

**Comment by romatitan** [comment]
For hover state as well, #ef4c28
![image](https://cloud.githubusercontent.com/assets/12888048/10751446/5206a40c-7cbb-11e5-8be3-06fad624e7b7.png)

**Comment by christiancebudigital** [comment]
this is fixed in my end. please clear cache..
